package lotto.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AutoLottoGenerator{

    private static final int LOTTO_SIZE = 6;

    public static List<LottoNumber> makeLotto() {
        List<LottoNumber> autoGeneratedLottoNumbers = new ArrayList<>();

        for (int key : LottoNumbers.lottoNumbers.keySet()) {
            autoGeneratedLottoNumbers.add(LottoNumbers.of(key));
        }

        Collections.shuffle(autoGeneratedLottoNumbers);
        return autoGeneratedLottoNumbers.subList(0, LOTTO_SIZE);
    }
}
