-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 02:34:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lotto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lotto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lotto` DEFAULT CHARACTER SET utf8 ;
USE `Lotto` ;

-- -----------------------------------------------------
-- Table `Lotto`.`Lotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lotto`.`Lotto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lotto`.`LottoNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lotto`.`LottoNumber` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lotto_id` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lotto_id_idx` (`lotto_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `number_lotto_fk`
    FOREIGN KEY (`lotto_id`)
    REFERENCES `Lotto`.`Lotto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lotto`.`WinningLotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lotto`.`WinningLotto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lotto_id` INT NULL,
  `bonusBall` INT NULL,
  `creat_time` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `lotto_id_idx` (`lotto_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `winning_lotto_fk`
    FOREIGN KEY (`lotto_id`)
    REFERENCES `Lotto`.`Lotto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lotto`.`LottoGame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lotto`.`LottoGame` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `winning_id` INT NULL,
  `lotto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `statistics_lotto_fk_idx` (`lotto_id` ASC),
  INDEX `result_winning_fk_idx` (`winning_id` ASC),
  CONSTRAINT `result_lotto_fk`
    FOREIGN KEY (`lotto_id`)
    REFERENCES `Lotto`.`Lotto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `result_winning_fk`
    FOREIGN KEY (`winning_id`)
    REFERENCES `Lotto`.`WinningLotto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
