package lotto.domain.utils;

import lotto.domain.Number;
import org.junit.Test;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

public class AutoLottoGeneratorTest {

    List<Number> autoGeneratedLottoNumbers = AutoLottoGenerator.makeLotto();

    @Test
    public void auto_로또_번호_생성_확인() {
        int lottoNumberSize = autoGeneratedLottoNumbers.size();
        assertThat(lottoNumberSize).isEqualTo(6);
    }

    @Test
    public void auto_로또_번호_중복_유무_확인() {
        Set<Number> lottoNumberSet = new HashSet<>();
        for (Number lottoNumber : autoGeneratedLottoNumbers) {
            lottoNumberSet.add(lottoNumber);
        }
        assertThat(lottoNumberSet.size()).isEqualTo(6);
    }
}
