package lotto.domain.utils;

import lotto.domain.model.Lotto;
import lotto.domain.model.Number;
import lotto.domain.model.NumberSet;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AutoLottoGenerator{

    private static final int LOTTO_SIZE = 6;

    public static Lotto makeLotto() {
        List<Number> autoGeneratedLottoNumbers = new ArrayList<>();

        for (int key : NumberSet.lottoNumbers.keySet()) {
            autoGeneratedLottoNumbers.add(NumberSet.of(key));
        }

        Collections.shuffle(autoGeneratedLottoNumbers);
        return new Lotto(autoGeneratedLottoNumbers.subList(0, LOTTO_SIZE));
    }
}
