-- MySQL Script generated by MySQL Workbench
-- Sun Jun 23 23:57:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lotto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lotto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lotto` DEFAULT CHARACTER SET utf8 ;
USE `lotto` ;

-- -----------------------------------------------------
-- Table `lotto`.`round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`round` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotto`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotto`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `lotto_number` VARCHAR(50) NOT NULL,
  `round_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `fk_purchase_round1_idx` (`round_id` ASC) VISIBLE,
  INDEX `fk_purchase_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `lotto`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `lotto`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotto`.`winning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`winning` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lotto_number` VARCHAR(50) NOT NULL,
  `bonus_number` VARCHAR(5) NOT NULL,
  `round_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_winning_round1_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `fk_winning_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `lotto`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotto`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lotto_rank` VARCHAR(10) NOT NULL,
  `lotto_match_count` INT NOT NULL,
  `round_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_result_round1_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `fk_result_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `lotto`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotto`.`yield`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lotto`.`yield` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lotto_yield` BIGINT NOT NULL,
  `round_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_yield_round1_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `fk_yield_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `lotto`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into type values(0, "수동");
insert into type values(0, "자동");